In [1]:
import numpy as np
arr = np.random.randint(10, 100, 10)
print("Array:", arr)
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
reshaped = arr.reshape(2,5)
print("Reshaped (2x5):\n", reshaped)
print("Second Row:", reshaped[1])
print("Identity Matrix:\n", np.eye(3))


Array: [48 58 21 43 96 80 22 61 77 10]
Mean: 51.6
Max: 96
Min: 10
Reshaped (2x5):
 [[48 58 21 43 96]
 [80 22 61 77 10]]
Second Row: [80 22 61 77 10]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
import pandas as pd
data = {
    'Name': ['Amit', 'Riya', 'Karan', 'Siddhi', 'Anya'],
    'Marks': [88, 92, 79, 95, 84],
    'Age': [20, 21, 19, 22, 20],
    'City': ['Delhi', 'Mumbai', 'Pune', 'Delhi', 'Pune']
}
df = pd.DataFrame(data)
print(df)
print(df.describe())
print(df[df['Marks'] > 85])
df['Grade'] = ['A' if m >= 90 else 'B' for m in df['Marks']]
print(df)
print("Average Marks:", df['Marks'].mean())


     Name  Marks  Age    City
0    Amit     88   20   Delhi
1    Riya     92   21  Mumbai
2   Karan     79   19    Pune
3  Siddhi     95   22   Delhi
4    Anya     84   20    Pune
           Marks        Age
count   5.000000   5.000000
mean   87.600000  20.400000
std     6.348228   1.140175
min    79.000000  19.000000
25%    84.000000  20.000000
50%    88.000000  20.000000
75%    92.000000  21.000000
max    95.000000  22.000000
     Name  Marks  Age    City
0    Amit     88   20   Delhi
1    Riya     92   21  Mumbai
3  Siddhi     95   22   Delhi
     Name  Marks  Age    City Grade
0    Amit     88   20   Delhi     B
1    Riya     92   21  Mumbai     A
2   Karan     79   19    Pune     B
3  Siddhi     95   22   Delhi     A
4    Anya     84   20    Pune     B
Average Marks: 87.6


In [9]:
import pandas as pd
data={
    'Name':['amit','siddhi','kapish','nidhi','pitam'] ,
    'Marks':[88,92,79,95,84],
    'Age':[20,21,13,23,26],
    'City':['Pune','Delhi','Haryana','Mumbai','Rajasthan']
}
df=pd.DataFrame(data)
print(df)
print(df.loc[df['Marks'].idxmax()])
print(df['Age'].mean())
df['City'].value_counts()

     Name  Marks  Age       City
0    amit     88   20       Pune
1  siddhi     92   21      Delhi
2  kapish     79   13    Haryana
3   nidhi     95   23     Mumbai
4   pitam     84   26  Rajasthan
Name      nidhi
Marks        95
Age          23
City     Mumbai
Name: 3, dtype: object
20.6


City
Pune         1
Delhi        1
Haryana      1
Mumbai       1
Rajasthan    1
Name: count, dtype: int64